Spinning up fresh Docker containres script
eleftrik/laradhoc pull request #15
Opened 2024-08-20 12:29 UTC by xnekv03

I made this scripts for my myself and found it useful especially when I work on multiple PCs
Please consider merging to the main branch

Thank you

2024-08-21 08:16 UTC, eleftrik commented
Hi @xnekv03 and thanks for your PR.
Just two small reviews. Could you please
- fix typos
- move your script inside `bin/` folder
?

Thanks!

2024-08-21 08:38 UTC, xnekv03 commented
Hi @eleftrik,
sorry for typos. Fixed

2024-08-21 14:29 UTC, xnekv03 commented
Adding intl extension to Dockerfile

2024-08-21 14:36 UTC, eleftrik requested changes

2024-08-21 14:36 UTC, eleftrik commented on README.md
> +sh .\.docker\scripts\rundocker.sh
@xnekv03 I think `/` should be used.

2024-08-21 14:40 UTC, xnekv03 commented on README.md
> +sh .\.docker\scripts\rundocker.sh
changed, however works both ways

2024-08-22 09:14 UTC, merged

2024-08-22 09:15 UTC, eleftrik commented
@xnekv03 Thanks!